### ISSUE TITLE
店铺签到报错jd_dpqd.js

### ISSUE THREAD

**Issue by AidenHuo** [feverrun/my_scripts#8]
报错：
活动太火爆了

TypeError: Cannot read properties of null (reading '1')
    at /ql/data/scripts/shufflewzc_faker3_main/jd_m_sign.swap.js:108:81
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/shufflewzc_faker3_main/jd_m_sign.swap.js:244:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

另外问一下dpqd_token，token是指activityID吗？
支持这种吗？店铺签到里边都会先选择“我已阅读并知晓”，然后点击按钮“知道了，继续签到”。

**Comment by feverrun** [comment]
你是不是问错地方了？ shufflewzc_faker3_main 不是我的
